In [9]:
import torch 

n = 20 

perms = torch.stack([torch.randperm(5) for _ in range(n)])
value_mask = perms < 2 

contract_candidates = torch.randint(20, size=(n, 2))
high_settlement = torch.randint(2, size=(n,)).bool()
settle_value = torch.where(high_settlement, contract_candidates.max(-1)[0], contract_candidates.min(-1)[0])
torch.cat([contract_candidates, high_settlement.unsqueeze(-1), settle_value.unsqueeze(-1)], dim=-1)

tensor([[11, 18,  0, 11],
        [ 1,  3,  0,  1],
        [18,  1,  0,  1],
        [16,  8,  1, 16],
        [ 7,  9,  1,  9],
        [ 2,  2,  1,  2],
        [10, 13,  0, 10],
        [12,  9,  1, 12],
        [19,  9,  1, 19],
        [13,  3,  1, 13],
        [ 9,  9,  1,  9],
        [ 4,  0,  1,  4],
        [13, 12,  1, 13],
        [10, 15,  0, 10],
        [17,  3,  0,  3],
        [ 3, 16,  0,  3],
        [10, 19,  1, 19],
        [10, 15,  0, 10],
        [ 9, 17,  1, 17],
        [ 3, 12,  1, 12]])

In [11]:
info_roles = perms.clone()
value_mask = info_roles < 2 
is_chosen_mask = (contract_candidates == settle_value.unsqueeze(-1))
info_roles

tensor([[1, 3, 4, 0, 2],
        [3, 1, 0, 4, 2],
        [1, 3, 2, 0, 4],
        [2, 3, 4, 0, 1],
        [0, 3, 1, 4, 2],
        [0, 2, 4, 3, 1],
        [4, 3, 0, 1, 2],
        [2, 0, 1, 4, 3],
        [0, 3, 1, 4, 2],
        [4, 1, 3, 2, 0],
        [1, 2, 4, 0, 3],
        [4, 0, 3, 2, 1],
        [2, 1, 0, 4, 3],
        [2, 3, 0, 4, 1],
        [0, 1, 3, 4, 2],
        [0, 4, 3, 1, 2],
        [4, 1, 3, 0, 2],
        [2, 4, 0, 1, 3],
        [1, 4, 2, 3, 0],
        [4, 2, 1, 3, 0]])

In [23]:
info_roles = perms.clone()

# Create masks for positions 0 and 1 in the permutation
pos_0_mask = (perms == 0)
pos_1_mask = (perms == 1)

# Check which contracts were chosen
first_chosen = (contract_candidates[:, 0] == settle_value)
second_chosen = (contract_candidates[:, 1] == settle_value)

# Update info_roles where original value was 0
info_roles[pos_0_mask] = torch.where(first_chosen, 0, 1).repeat_interleave(5).reshape(n, 5)[pos_0_mask]

# Update info_roles where original value was 1  
info_roles[pos_1_mask] = torch.where(second_chosen, 0, 1).repeat_interleave(5).reshape(n, 5)[pos_1_mask]

In [24]:
info_roles[:10], perms[:10]

(tensor([[1, 3, 4, 0, 2],
         [3, 1, 0, 4, 2],
         [0, 3, 2, 1, 4],
         [2, 3, 4, 0, 1],
         [1, 3, 0, 4, 2],
         [0, 2, 4, 3, 0],
         [4, 3, 0, 1, 2],
         [2, 0, 1, 4, 3],
         [0, 3, 1, 4, 2],
         [4, 1, 3, 2, 0]]),
 tensor([[1, 3, 4, 0, 2],
         [3, 1, 0, 4, 2],
         [1, 3, 2, 0, 4],
         [2, 3, 4, 0, 1],
         [0, 3, 1, 4, 2],
         [0, 2, 4, 3, 1],
         [4, 3, 0, 1, 2],
         [2, 0, 1, 4, 3],
         [0, 3, 1, 4, 2],
         [4, 1, 3, 2, 0]]))

In [20]:
info_roles.at(value_mask)

AttributeError: 'Tensor' object has no attribute 'at'